# Generated by Django 4.2.5 on 2023-10-01 11:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturedYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name_plural': 'manufactured_year',
                'db_table': 'manufactured_year',
            },
        ),
        migrations.CreateModel(
            name='ManufactureImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture_image', models.ImageField(upload_to='manufacture_images/')),
            ],
            options={
                'db_table': 'manufacture_images',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'marks',
                'db_table': 'mark',
            },
        ),
        migrations.CreateModel(
            name='Upload_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
            ],
            options={
                'verbose_name_plural': 'upload_file2021',
                'db_table': 'upload_file2021',
            },
        ),
        migrations.CreateModel(
            name='Upload_File2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files2/')),
            ],
            options={
                'verbose_name_plural': 'upload_file2022',
                'db_table': 'upload_file22',
            },
        ),
        migrations.CreateModel(
            name='Upload_File3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files3/')),
            ],
            options={
                'verbose_name_plural': 'upload_file2020',
                'db_table': 'upload_file2020',
            },
        ),
        migrations.CreateModel(
            name='Model1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='basic_app.mark')),
            ],
            options={
                'verbose_name_plural': 'models',
                'db_table': 'model1',
            },
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('manufactured_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.manufacturedyear')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.mark')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.model1')),
            ],
            options={
                'verbose_name_plural': 'manufacture',
                'db_table': 'manufacture',
            },
        ),
        migrations.CreateModel(
            name='DATA22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True, verbose_name='data yaratilgan vaqti')),
                ('sana', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField(default=0)),
                ('mode', models.CharField(max_length=20, null=True)),
                ('cost', models.FloatField(default=0)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.upload_file2')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.mark')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data22', to='basic_app.model1')),
            ],
            options={
                'verbose_name_plural': 'data2022',
                'db_table': 'data2022',
            },
        ),
        migrations.CreateModel(
            name='DATA21',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True, default=datetime.datetime.now, verbose_name='data yaratilgan vaqti')),
                ('sana', models.DateField()),
                ('product_count', models.PositiveIntegerField(default=0)),
                ('mode', models.CharField(max_length=20, null=True)),
                ('cost', models.FloatField(default=0)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.upload_file')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.mark')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data21', to='basic_app.model1')),
            ],
            options={
                'verbose_name_plural': 'data2021',
                'db_table': 'data2021',
            },
        ),
        migrations.CreateModel(
            name='Data20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_created=True, default=datetime.date.today, verbose_name='data yaratilgan vaqt')),
                ('sana', models.DateField()),
                ('country', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField(default=0)),
                ('mode', models.CharField(max_length=20, null=True)),
                ('cost', models.FloatField(default=0)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.upload_file3')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.mark')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data20', to='basic_app.model1')),
            ],
            options={
                'verbose_name_plural': 'data2020',
                'db_table': 'data2020',
            },
        ),
    ]
