# Generated by Django 4.2.5 on 2023-10-11 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_upload_file4_data16'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data16',
            name='file_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.upload_file4'),
        ),
        migrations.AlterField(
            model_name='data16',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.model1'),
        ),
    ]
