# Generated by Django 4.2.5 on 2023-12-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_upload_file5_data19'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data19',
            old_name='counrty',
            new_name='country',
        ),
    ]
