# Generated by Django 4.2.5 on 2023-12-18 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_rename_counrty_data19_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload_file5',
            options={'verbose_name_plural': 'upload_file2019'},
        ),
        migrations.AlterModelTable(
            name='upload_file5',
            table='upload_file2019',
        ),
    ]
