# Generated by Django 4.2.5 on 2023-12-18 16:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_data19_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_File6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files6/')),
            ],
            options={
                'verbose_name_plural': 'upload_file2023',
                'db_table': 'upload_file2023',
            },
        ),
        migrations.CreateModel(
            name='Data23',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_created=True, default=datetime.date.today, verbose_name='yaratilgan vaqt')),
                ('mode', models.CharField(max_length=20, null=True)),
                ('sana', models.DateField()),
                ('country', models.CharField(max_length=20, null=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.upload_file6')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.mark')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data23', to='basic_app.model1')),
            ],
            options={
                'verbose_name_plural': 'data2023',
                'db_table': 'data2023',
            },
        ),
    ]
