# Generated by Django 4.2.5 on 2023-12-19 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0009_upload_file6_data23'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload_file4',
            options={'verbose_name_plural': 'upload_file_2016'},
        ),
        migrations.AlterModelTable(
            name='upload_file4',
            table='upload_file_2016',
        ),
    ]
