# Generated by Django 4.2.5 on 2023-12-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_alter_upload_file4_options_alter_upload_file4_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data19',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='data23',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
