# Generated by Django 4.2.5 on 2023-12-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0011_alter_data19_country_alter_data23_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('mark_name_for_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_app.mark')),
            ],
            options={
                'verbose_name_plural': 'images',
                'db_table': 'images',
            },
        ),
    ]
