# Generated by Django 4.2.5 on 2024-03-23 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0012_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data23',
            name='file_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_app.upload_file6'),
        ),
    ]
