# Generated by Django 4.2.5 on 2024-03-23 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0014_alter_data22_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data19',
            name='file_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_app.upload_file5'),
        ),
        migrations.AlterField(
            model_name='data20',
            name='file_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_app.upload_file3'),
        ),
        migrations.AlterField(
            model_name='data21',
            name='file_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_app.upload_file'),
        ),
        migrations.AlterField(
            model_name='data22',
            name='file_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_app.upload_file2'),
        ),
    ]
