# Generated by Django 4.2.5 on 2024-03-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0015_alter_data19_file_id_alter_data20_file_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data19',
            name='sana',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data20',
            name='sana',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data21',
            name='sana',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data22',
            name='sana',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data23',
            name='sana',
            field=models.DateField(blank=True, null=True),
        ),
    ]
